export const interviewQuestions: Record<string, string[]> = {
  life: [
    "Where were you born, and what was it like growing up there?",
    "What is your earliest memory?",
    "Who had the biggest influence on who you became?",
    "What was your family like when you were young?",
    "What is a moment in your life you'll never forget?",
    "What is the hardest thing you've ever been through, and how did you get past it?",
    "What are you most proud of in your life?",
    "What do you wish you had done differently?",
    "What does a perfect day look like for you?",
    "What do you hope people remember about you?",
    "If you could go back and give your younger self one piece of advice, what would it be?",
    "What has been the greatest surprise of your life?",
  ],
  childhood: [
    "What was your home like when you were growing up?",
    "What were your parents like? What do you remember most about them?",
    "Did you have brothers or sisters? What was your relationship with them?",
    "What games or activities did you love as a kid?",
    "Who was your best friend growing up, and what did you do together?",
    "What was school like for you?",
    "What was your favorite meal your family made?",
    "Did your family have any traditions or routines you looked forward to?",
    "What got you in trouble as a kid?",
    "What was the neighborhood like where you grew up?",
    "Is there a family story that gets told over and over?",
    "What do you miss most about your childhood?",
  ],
  love: [
    "How did you meet the love of your life?",
    "What was your first impression of them?",
    "What was your first date like?",
    "When did you know this was the person you wanted to be with?",
    "What was the proposal like, or how did you decide to be together?",
    "What was your wedding day like?",
    "What's the funniest thing that's happened in your relationship?",
    "What has been the hardest time you went through together?",
    "What's the most important thing you've learned about love?",
    "What do you admire most about your partner?",
    "What would you want your children to know about love?",
    "What's a small, everyday moment with your partner that means the world to you?",
  ],
  career: [
    "What was your very first job?",
    "What did you dream of being when you were young?",
    "How did you end up in the career you had?",
    "What was a typical day at work like?",
    "Who was the most important mentor or boss you ever had?",
    "What moment in your career are you most proud of?",
    "Was there a time you failed or things didn't go as planned? What happened?",
    "What was the biggest risk you ever took professionally?",
    "How did your work affect your family life?",
    "What did you learn about yourself through your work?",
    "If you could do it all over, would you choose the same path?",
    "What advice would you give someone just starting out in their career?",
  ],
  letters: [
    "What do you want your children to always remember?",
    "What advice would you give your grandchildren about life?",
    "What values do you hope your family carries forward?",
    "What is something about you that your family might not know?",
    "What do you want to say to your partner that you haven't said enough?",
    "Is there anyone you'd like to forgive or ask forgiveness from?",
    "What traditions do you hope your family keeps alive?",
    "What has brought you the most joy in life?",
    "What do you want your family to know about where they come from?",
    "If you could write a letter to someone who has passed, what would you say?",
    "What gives you hope for the future?",
    "What is the most important thing you've learned in your life?",
  ],
};
